const equipes = [
  {
    id: 1,
    nome: 'Bauru',
    nomeCompleto: 'Associação Bauru Basketball Team',
    localizacao: 'Bauru, SP, Brasil',
    imagem: 'images/bauru.png',
    mascote: 'Dunk',
    fundacao: 1994,
    arena: 'Ginásio Panela de Pressão',
    capacidadeArena: '2000 espectadores',
    materialEsportivo: 'RR Uniformes',
    site: 'www.baurubasket.com.br'
  },
  {
    id: 2,
    nome: 'Brb/Brasília',
    nomeCompleto: 'LB Produções e Eventos LTDA - ME',
    localizacao: 'Brasília, DF, Brasil',
    imagem: 'images/brb.png',
    mascote: 'Spooky',
    fundacao: 2018,
    arena: 'Ginásio Nilson Nelson',
    capacidadeArena: '11.397 espectadores',
    materialEsportivo: 'Astro Sport',
    site: 'www.bsbbkt.com'
  },
  {
    id: 3,
    nome: 'Caxias do Sul Basquete',
    nomeCompleto: 'Caxias do Sul Basquete Associação Esportiva e Recreativa',
    localizacao: 'Caxias do Sul, RS, Brasil',
    imagem: 'images/caxias.png',
    mascote: 'Gambasquete',
    fundacao: 2006,
    arena: 'Ginásio do Sesi',
    capacidadeArena: '4.500 espectadores',
    materialEsportivo: 'Catera Esportes',
    site: 'www.caxiasdosulbasquete.com.br'
  },
  {
    id: 4,
    nome: 'Cerrado Basquete',
    nomeCompleto: 'Associação Esportiva e Recreativa Cerrado',
    localizacao: 'Brasília, DF, Brasil',
    imagem: 'images/cerrado.png',
    mascote: '',
    fundacao: 2016,
    arena: 'Ginásio da ASCEB',
    capacidadeArena: '1.100 espectadores',
    materialEsportivo: 'Overtime',
    site: 'www.cerradobasquete.com.br'
  },
  {
    id: 5,
    nome: 'Corinthians',
    nomeCompleto: 'Sport Club Corinthians Paulista',
    localizacao: 'São Paulo, SP, Brasil',
    imagem: 'images/corinthians.png',
    mascote: 'Mosqueteiro',
    fundacao: 1928,
    arena: 'Ginásio Wlamir Marques',
    capacidadeArena: '6.500 espectadores',
    materialEsportivo: 'Nike',
    site: 'www.corinthians.com.br'
  },
  {
    id: 6,
    nome: 'Flamengo',
    nomeCompleto: 'Clube de Regatas do Flamengo',
    localizacao: 'Rio de Janeiro, RJ, Brasil',
    imagem: 'images/flamengo.png',
    mascote: 'Urubu',
    fundacao: 1919,
    arena: 'Ginásio Maracanãzinho',
    capacidadeArena: '11.800 espectadores',
    materialEsportivo: 'Adidas',
    site: 'www.flamengobasquete.com.br'
  },
  {
    id: 7,
    nome: 'Fortaleza Basquete Cearense',
    nomeCompleto: 'Associação de Basquete Cearense',
    localizacao: 'Fortaleza, CE, Brasil',
    imagem: 'images/fortaleza.png',
    mascote: 'Carcará',
    fundacao: 2012,
    arena: 'Arena do Centro de Formação Olímpica',
    capacidadeArena: '17.100 espectadores',
    materialEsportivo: 'Leão 1918',
    site: 'www.soucarcara.com.br'
  },
  {
    id: 8,
    nome: 'Sesi Franca',
    nomeCompleto: 'Franca Basquetebol Clube',
    localizacao: 'Franca, SP, Brasil',
    imagem: 'images/franca.png',
    mascote: 'Carcará',
    fundacao: 1959,
    arena: 'Ginásio Poliesportivo Pedro Morilla Fuentes',
    capacidadeArena: '6.000 espectadores',
    materialEsportivo: 'Overtime',
    site: 'www.francabasquete.com.br'
  },
  {
    id: 9,
    nome: 'Luvix/União Corinthians',
    nomeCompleto: 'Esporte Clube União Corinthians',
    localizacao: 'Santa Cruz do Sul, RS, Brasil',
    imagem: 'images/luvix.png',
    mascote: '',
    fundacao: 1959,
    arena: 'Ginásio Poliesportivo Arnão',
    capacidadeArena: '6.000 espectadores',
    materialEsportivo: 'SS Sports',
    site: 'www.basquete.uniaocorinthians.com.br'
  },
  {
    id: 10,
    nome: 'Minas Storm',
    nomeCompleto: 'Minas Storm Tênis Clube multi-sports club',
    localizacao: 'Belo Horizonte, Brazil',
    imagem: 'images/minas.png',
    mascote: '',
    fundacao: 1937,
    arena: 'Arena MTC',
    capacidadeArena: '4.000 espectadores',
    materialEsportivo: 'icone',
    site: 'www.minastenisclube.com.br/esportes/basquete'
  },
  {
    id: 11,
    nome: 'Mogi',
    nomeCompleto: 'Associação Desportiva de Mogi das Cruzes',
    localizacao: 'Mogi das Cruzes, SP, Brasil',
    imagem: 'images/mogi.png',
    mascote: 'Jaguá',
    fundacao: 1995,
    arena: 'Ginásio Municipal Professor Hugo Ramos',
    capacidadeArena: '5.000 espectadores',
    materialEsportivo: 'Overtime',
    site: 'www.mogidascruzesbasquete.com.br'
  },
  {
    id: 12,
    nome: 'Pato Basquete',
    nomeCompleto: 'Associação Basquetebol Arte de Pato Branco',
    localizacao: 'Pato Branco, PR, Brasil',
    imagem: 'images/pato.png',
    mascote: 'Pato',
    fundacao: 1999,
    arena: 'Ginásio do SESI',
    capacidadeArena: '1.000 espectadores',
    materialEsportivo: 'gr sports',
    site: 'www.patobasquete.com.br'
  },
  {
    id: 13,
    nome: 'Paulistano',
    nomeCompleto: 'Club Athletico Paulistano',
    localizacao: 'São Paulo, SP, Brasil',
    imagem: 'images/paulistano.png',
    mascote: 'Fried',
    fundacao: 1922,
    arena: 'Ginásio Antônio Prado Junior',
    capacidadeArena: '1.280 espectadores',
    materialEsportivo: 'Undici',
    site: 'www.paulistano.org.br'
  },
  {
    id: 14,
    nome: 'Pinheiros',
    nomeCompleto: 'Esporte Clube Pinheiros',
    localizacao: 'São Paulo, SP, Brasil',
    imagem: 'images/pinheiros.png',
    mascote: '',
    fundacao: 1926,
    arena: 'Ginásio Poliesportivo Henrique Villaboim',
    capacidadeArena: '850 espectadores',
    materialEsportivo: 'Undici',
    site: 'www.ecp.org.br/basquete'
  },
  {
    id: 15,
    nome: 'Rio Claro',
    nomeCompleto: 'Associação Beneficente Cultural Desportiva Bandeirantes',
    localizacao: 'Rio Claro, SP, Brasil',
    imagem: 'images/rio-claro.png',
    mascote: 'Leônidas',
    fundacao: 1981,
    arena: 'Ginásio Felipe Karan',
    capacidadeArena: '2.200 espectadores',
    materialEsportivo: 'Undici',
    site: 'www.rioclarobasquete.com.br'
  },
  {
    id: 16,
    nome: 'São Paulo',
    nomeCompleto: 'São Paulo Futebol Clube',
    localizacao: 'São Paulo, SP, Brasil',
    imagem: 'images/sao-paulo.png',
    mascote: 'São Paulo (santo)',
    fundacao: 1930,
    arena: 'Ginásio Antônio Leme Nunes Galvão',
    capacidadeArena: '1.918 espectadores',
    materialEsportivo: 'Adidas',
    site: 'www.saopaulofc.net/basquete'
  },
  {
    id: 17,
    nome: 'Unifacisa',
    nomeCompleto: 'Associação Atlético Unifacisa',
    localizacao: 'Campina Grande, PB, Brasil',
    imagem: 'images/unifacisa.png',
    mascote: 'Jack',
    fundacao: 2012,
    arena: 'Arena Unifacisa',
    capacidadeArena: '1.200 espectadores',
    materialEsportivo: 'Overtime',
    site: 'www.unifacisa.edu.br/basquete'
  }
];

export default equipes;
